version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    restart: on-failure
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    secrets:
      - db_password
      - db_root_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
volumes:
  mariadb_data:

