version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    restart: on-failure
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=/run/secrets/db_password
      - MYSQL_ROOT_PASSWORD=/run/secrets/db_root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    secrets:
      - db_password
      - db_root_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress:
    build: ./requirements/wordpress
    restart: on-failure
    depends_on:
      - mariadb
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=/run/secrets/wp_admin_password
      - WP_USER_PASS=/run/secrets/wp_user_password
      - WP_EMAIL=${WP_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - PHP_PORT=9000
      - WP_PATH=/var/www/html
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  mariadb_data:
  wordpress_data:

